/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.
import { Route as rootRouteImport } from './routes/__root';
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml';
import { Route as SearchRouteImport } from './routes/search';
import { Route as LoginRouteImport } from './routes/login';
import { Route as CategoriesRouteImport } from './routes/categories';
import { Route as ArticlesRouteImport } from './routes/articles';
import { Route as IndexRouteImport } from './routes/index';
import { Route as WriteIndexRouteImport } from './routes/write.index';
import { Route as CategoriesIndexRouteImport } from './routes/categories.index';
import { Route as ArticlesIndexRouteImport } from './routes/articles.index';
import { Route as AdminIndexRouteImport } from './routes/admin.index';
import { Route as CategoriesSlugRouteImport } from './routes/categories.$slug';
import { Route as AuthorsUsernameRouteImport } from './routes/authors.$username';
import { Route as ArticlesSlugRouteImport } from './routes/articles.$slug';
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
    id: '/sitemap.xml',
    path: '/sitemap.xml',
    getParentRoute: () => rootRouteImport,
});
const SearchRoute = SearchRouteImport.update({
    id: '/search',
    path: '/search',
    getParentRoute: () => rootRouteImport,
});
const LoginRoute = LoginRouteImport.update({
    id: '/login',
    path: '/login',
    getParentRoute: () => rootRouteImport,
});
const CategoriesRoute = CategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => rootRouteImport,
});
const ArticlesRoute = ArticlesRouteImport.update({
    id: '/articles',
    path: '/articles',
    getParentRoute: () => rootRouteImport,
});
const IndexRoute = IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => rootRouteImport,
});
const WriteIndexRoute = WriteIndexRouteImport.update({
    id: '/write/',
    path: '/write/',
    getParentRoute: () => rootRouteImport,
});
const CategoriesIndexRoute = CategoriesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => CategoriesRoute,
});
const ArticlesIndexRoute = ArticlesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ArticlesRoute,
});
const AdminIndexRoute = AdminIndexRouteImport.update({
    id: '/admin/',
    path: '/admin/',
    getParentRoute: () => rootRouteImport,
});
const CategoriesSlugRoute = CategoriesSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => CategoriesRoute,
});
const AuthorsUsernameRoute = AuthorsUsernameRouteImport.update({
    id: '/authors/$username',
    path: '/authors/$username',
    getParentRoute: () => rootRouteImport,
});
const ArticlesSlugRoute = ArticlesSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => ArticlesRoute,
});
const ArticlesRouteChildren = {
    ArticlesSlugRoute: ArticlesSlugRoute,
    ArticlesIndexRoute: ArticlesIndexRoute,
};
const ArticlesRouteWithChildren = ArticlesRoute._addFileChildren(ArticlesRouteChildren);
const CategoriesRouteChildren = {
    CategoriesSlugRoute: CategoriesSlugRoute,
    CategoriesIndexRoute: CategoriesIndexRoute,
};
const CategoriesRouteWithChildren = CategoriesRoute._addFileChildren(CategoriesRouteChildren);
const rootRouteChildren = {
    IndexRoute: IndexRoute,
    ArticlesRoute: ArticlesRouteWithChildren,
    CategoriesRoute: CategoriesRouteWithChildren,
    LoginRoute: LoginRoute,
    SearchRoute: SearchRoute,
    SitemapDotxmlRoute: SitemapDotxmlRoute,
    AuthorsUsernameRoute: AuthorsUsernameRoute,
    AdminIndexRoute: AdminIndexRoute,
    WriteIndexRoute: WriteIndexRoute,
};
export const routeTree = rootRouteImport
    ._addFileChildren(rootRouteChildren)
    ._addFileTypes();
